---
name: "pr-issues-project"

on:
  issues:
    types:
    - opened
    - reopened
  pull_request:
    types:
    - opened
    - reopened

jobs:
  pr-issues-project:
    uses: schrodingers-stack/github-actions-workflows/.github/workflows/pr-issues-project.yaml@main
    secrets:
      SCHTACK_MAINTAINER_APP_ID: ${{ secrets.SCHTACK_MAINTAINER_APP_ID }}
      SCHTACK_MAINTAINER_PRIVATE_KEY: ${{ secrets.SCHTACK_MAINTAINER_PRIVATE_KEY }}
